Algoritmo "Exercicio_14"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Verificar se o valor é maior que 10.
// Autor(a)    : Laura Almeida Gomes
// Data atual  : 26/09/2026
Var
// Seção de Declarações das variáveis
   valor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um valor: ")
   leia(valor)

   se valor > 10 entao
      escreva("É MAIOR QUE 10!")
   senao
      escreva("NÃO É MAIOR QUE 10!")
   fimse
Fimalgoritmo