Algoritmo "Extra_A"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Produto do 1º com o 3º e soma do 2º com o 4º valor.
// Autor(a)    : Laura Almeida Gomes
// Data atual  : 20/09/2026
Var
// Seção de Declarações das variáveis
   A, B, C, D, P, S: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor de A: ")
   leia(A)
   escreva("Digite o valor de B: ")
   leia(B)
   escreva("Digite o valor de C: ")
   leia(C)
   escreva("Digite o valor de D: ")
   leia(D)

   P <- A * C
   S <- B + D

   escreval("O produto do primeiro com o terceiro valor (P) é: ", P)
   escreval("A soma do segundo com o quarto valor (S) é: ", S)
Fimalgoritmo