Algoritmo "L01G"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Propriedade distributiva (soma e multiplicação) para 4 números.
// Autor(a)    : Laura Almeida Gomes
// Data atual  : 20/09/2026
Var
// Seção de Declarações das variáveis
   A, B, C, D: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite o valor de A: ")
   leia(A)
   escreva("Digite o valor de B: ")
   leia(B)
   escreva("Digite o valor de C: ")
   leia(C)
   escreva("Digite o valor de D: ")
   leia(D)

   escreval("--- ADIÇÕES ---")
   escreval("A + B = ", A + B)
   escreval("A + C = ", A + C)
   escreval("A + D = ", A + D)
   escreval("B + C = ", B + C)
   escreval("B + D = ", B + D)
   escreval("C + D = ", C + D)

   escreval("--- MULTIPLICAÇÕES ---")
   escreval("A * B = ", A * B)
   escreval("A * C = ", A * C)
   escreval("A * D = ", A * D)
   escreval("B * C = ", B * C)
   escreval("B * D = ", B * D)
   escreval("C * D = ", C * D)
Fimalgoritmo