Algoritmo "L03A"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar a tabuada de um número utilizando o laço enquanto.
// Autor(a)    : Laura Almeida Gomes
// Data atual  : 25/09/2026
Var
// Seção de Declarações das variáveis
   N, i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Digite um número para ver sua tabuada: ")
   leia(N)

   i <- 1
   enquanto i <= 10 faca
      escreval(N, " x ", i, " = ", N * i)
      i <- i + 1
   fimenquanto
Fimalgoritmo