Algoritmo "L04A"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Apresentar os quadrados dos números inteiros de 15 a 200.
// Autor(a)    : Laura Almeida Gomes
// Data atual  : 26/09/2026
Var
// Seção de Declarações das variáveis
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 15

   repita
      escreval("O quadrado de ", i, " é ", i * i)
      i <- i + 1
   ate i > 200
Fimalgoritmo